import { type FileSystemItem } from '../file-system-map';
import { ITEMS_MAP_ALL } from './all-items';

export const ITEMS_MAP_FAVORITES: FileSystemItem[] = [
  ITEMS_MAP_ALL['C:/USUARIOS/FITERMAN/AREA_DE_TRABALHO'],
  ITEMS_MAP_ALL['C:/USUARIOS/FITERMAN/DOCUMENTOS'],
  ITEMS_MAP_ALL['C:/USUARIOS/FITERMAN/IMAGENS'],
  ITEMS_MAP_ALL['C:/USUARIOS/FITERMAN/PROJETOS'],
  ITEMS_MAP_ALL['C:/USUARIOS/FITERMAN/DOWNLOADS'],
  ITEMS_MAP_ALL['C:/USUARIOS/FITERMAN/PROJETOS/SETEJANELAS/ABOUT.MD'],
  ITEMS_MAP_ALL['C:/USUARIOS/FITERMAN/DOCUMENTOS/SOBRE_MIM/README.PDF'],
  ITEMS_MAP_ALL['C:/USUARIOS/FITERMAN/DOCUMENTOS/SOBRE_MIM/CURRICULO.PDF'],
];
