import { type FileSystemItem } from '../file-system-map';
import {
  ITEMS_MAP_ABOUT_ME,
  ITEMS_MAP_DOCUMENTS,
  ITEMS_MAP_FAVORITES,
  ITEMS_MAP_FITERMAN,
  ITEMS_MAP_IMAGES,
  ITEMS_MAP_LIBS,
  ITEMS_MAP_PROJETO_1_CHALLENGELETT,
  ITEMS_MAP_PROJETO_2_LOCAWEB,
  ITEMS_MAP_PROJETO_3_LEAFLETZEN,
  ITEMS_MAP_PROJETO_4_SETEJANELAS,
  ITEMS_MAP_PROJETOS,
  ITEMS_MAP_ROOT,
  ITEMS_MAP_USERS,
  ITEMS_MAP_VIDEOS,
  ITEMS_MAP_WORKSPACE,
  ITEMS_MAP_SISTEMA_DE_ARQUIVOS,
} from './';

export const STRUCTURE_MAP_FILE_SYSTEM: Record<string, FileSystemItem[]> = {
  // ROOT LEVEL 0 [ DRIVE ROOT C: ]
  'C:': Object.values(ITEMS_MAP_ROOT),

  // ROOT LEVEL 2 [ USUÁRIOS ]
  'C:/USUARIOS': Object.values(ITEMS_MAP_USERS),

  // ROOT LEVEL 2 [ ARQUIVOS_DE_PROGRAMAS ]
  'C:/ARQUIVOS_DE_PROGRAMAS': Object.values(ITEMS_MAP_SISTEMA_DE_ARQUIVOS),

  // ROOT LEVEL 2 [ SISTEMA_DE_ARQUIVOS ]
  'C:/SISTEMA_DE_ARQUIVOS': Object.values(ITEMS_MAP_SISTEMA_DE_ARQUIVOS),

  // ROOT LEVEL 2 [ FITERMAN ]
  'C:/USUARIOS/FITERMAN': Object.values(ITEMS_MAP_FITERMAN),

  // ROOT LEVEL 3 [ FITERMAN/FAVORITOS ]
  'C:/USUARIOS/FITERMAN/FAVORITOS': ITEMS_MAP_FAVORITES,

  // ROOT LEVEL 3 [ FITERMAN/AREA_DE_TRABALHO ]
  'C:/USUARIOS/FITERMAN/AREA_DE_TRABALHO': ITEMS_MAP_WORKSPACE,

  // ROOT LEVEL 3 [ FITERMAN/BIBLIOTECAS ]
  'C:/USUARIOS/FITERMAN/BIBLIOTECAS': ITEMS_MAP_LIBS,

  // ROOT LEVEL 3 [ FITERMAN/COMPUTADOR ]
  'C:/USUARIOS/FITERMAN/COMPUTADOR': [],

  // ROOT LEVEL 3 [ FITERMAN/DOCUMENTOS ]
  'C:/USUARIOS/FITERMAN/DOCUMENTOS': Object.values(ITEMS_MAP_DOCUMENTS),

  // ROOT LEVEL 3 [ FITERMAN/DOWNLOADS ]
  'C:/USUARIOS/FITERMAN/DOWNLOADS': [],

  // ROOT LEVEL 3 [ FITERMAN/IMAGENS ]
  'C:/USUARIOS/FITERMAN/IMAGENS': Object.values(ITEMS_MAP_IMAGES),

  // ROOT LEVEL 3 [ FITERMAN/MÚSICAS ]
  'C:/USUARIOS/FITERMAN/MÚSICAS': [],

  // ROOT LEVEL 3 [ FITERMAN/PROJETOS ]
  'C:/USUARIOS/FITERMAN/PROJETOS': Object.values(ITEMS_MAP_PROJETOS),

  // ROOT LEVEL 3 [ FITERMAN/VIDEOS ]
  'C:/USUARIOS/FITERMAN/VIDEOS': Object.values(ITEMS_MAP_VIDEOS),

  // ROOT LEVEL 4 [ PROJETOS/CHALLENGE-LETT ]
  'C:/USUARIOS/FITERMAN/PROJETOS/CHALLENGELETT': Object.values(ITEMS_MAP_PROJETO_1_CHALLENGELETT),

  // ROOT LEVEL 4 [ PROJETOS/LOCAWEB ]
  'C:/USUARIOS/FITERMAN/PROJETOS/LOCAWEB': Object.values(ITEMS_MAP_PROJETO_2_LOCAWEB),

  // ROOT LEVEL 4 [ PROJETOS/LEAFLET-ZEN ]
  'C:/USUARIOS/FITERMAN/PROJETOS/LEAFLETZEN': Object.values(ITEMS_MAP_PROJETO_3_LEAFLETZEN),

  // ROOT LEVEL 4 [ PROJETOS/SETE-JANELAS ]
  'C:/USUARIOS/FITERMAN/PROJETOS/SETEJANELAS': Object.values(ITEMS_MAP_PROJETO_4_SETEJANELAS),

  // ROOT LEVEL 4 [ DOCUMENTOS/ABOUT_ME ]
  'C:/USUARIOS/FITERMAN/DOCUMENTOS/SOBRE_MIM': Object.values(ITEMS_MAP_ABOUT_ME),
};
