import { type FileSystemItem } from '../file-system-map';
import { ITEMS_MAP_ALL } from './all-items';

export const ITEMS_MAP_WORKSPACE: FileSystemItem[] = [
  // Diretórios
  ITEMS_MAP_ALL['C:/USUARIOS/FITERMAN/DOCUMENTOS/SOBRE_MIM'],
  ITEMS_MAP_ALL['C:/USUARIOS/FITERMAN/PROJETOS'],
  ITEMS_MAP_ALL['C:/USUARIOS/FITERMAN/PROJETOS/SETEJANELAS'],

  // Arquivos
  ITEMS_MAP_ALL['C:/USUARIOS/FITERMAN/DOCUMENTOS/SOBRE_MIM/README.PDF'],
  ITEMS_MAP_ALL['C:/USUARIOS/FITERMAN/DOCUMENTOS/SOBRE_MIM/CURRICULO.PDF'],
  ITEMS_MAP_ALL['C:/USUARIOS/FITERMAN/PROJETOS/SETEJANELAS/SETEJANELAS_ABOUT.PDF'],
];
